import base64

# test1 = 'MIICLTCCAZagAwIBAgIETerWzzANBgkqhkiG9w0BAQUFADBbMQswCQYDVQQGEwJVUzELMAkGA1UECBMCVkExDzANBgNVBAcTBlZpZW5uYTEMMAoGA1UEChMDUFNMMQswCQYDVQQLEwJQRTETMBEGA1UEAxMKdHh1ZS10MzUwMDAeFw0xMTA2MDUwMTA3MjdaFw0yMTA2MDIwMTA3MjdaMFsxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJWQTEPMA0GA1UEBxMGVmllbm5hMQwwCgYDVQQKEwNQU0wxCzAJBgNVBAsTAlBFMRMwEQYDVQQDEwp0eHVlLXQzNTAwMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDIdVOlRIcSuvEgGkZZnS0SwDPJkGTQuQSQ4tn3NV5dB8XvIRuTQ7a26x9fOC/2jSo3RZVLS5CFgy+17nVyEL01aYzKX/xy6EYANKlo0nAUi2NgFZ46//Rw2dksNpX92NVFuLAQXVv6ROENfd75a0+u3uomxpjhaYIXmjo3ERKNHQIDAQABMA0GCSqGSIb3DQEBBQUAA4GBAJqU1TBQ4WaV87n2Lf/YDHVRXItJW9tTZgesmFlA/rq42aybqgTuNKPizqhJ3nklOIIGIPPAZ7rCVV4TPYz/UH/mzhbs3MAIFsnAfFT37nar1WiYifXBNuGeTAhnZxJD/qHWdZSJmeQXt7OKIHQAYv9DdfcuYBC9PfNERkwK6FPB'.encode('utf-8')
# base64_bytes = base64.b64decode(test1)
# test2 = base64_bytes#.decode('utf-8', errors='ignore')
# print(test2.decode('utf-8', errors='ignore'))
# file = open("D:/mmatv.jpg", "wb")
# file.write(test2)
# file.close()
print(base64.b64encode("novolipets:novolipets".encode('utf-8')))
